/*!
  GymHolic Terms & Conditions
  — Used for Google Cloud OAuth verification and public site compliance.
  This page is publicly accessible without authentication.
*/

import Layout from "@/app/layout";

export default function TermsPage() {
  return (
    <Layout>
      <main className="prose lg:prose-xl max-w-2xl mx-auto py-12">
        <h1 className="text-3xl font-bold tracking-tight mb-6">
          Terms & Conditions
        </h1>

        <p className="mb-6">
          Last updated: August 14, 2026
        </p>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            Overview
          </h2>

          <p className="mb-6">
            These Terms & Conditions govern the use of GymHolic, a gym consulting
            and booking platform provided by GymHolic. By accessing or otherwise
            using the GymHolic website, you agree to comply with these Terms &
            Conditions. If you disagree with any part of the terms, you may not
            access the service.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            Account Registration
          </h2>

          <p className="mb-6">
            To access certain features of GymHolic, you may be required to register
            an account. When you register, you agree to provide accurate, current,
            and complete information. You are responsible for maintaining the
            security of your account and password. You agree to accept
            responsibility for all activities that occur under your account.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            Booking and Consultations
          </h2>

          <p className="mb-6">
            GymHolic facilitates bookings and consultations between experts and
            clients. All bookings are subject to the expert's availability and
            terms. Clients are responsible for providing accurate information
            when making bookings.
          </p>

          <h3 className="text-xl font-medium mb-3">
            Consultation Types
          </h3>

          <p className="mb-6">
            Consultations may be conducted online via Google Meet, on-site at the
            expert's facility, or through other agreed-upon methods. The format
            will be agreed upon between the expert and client prior to booking.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            Google Services
          </h2>

          <p className="mb-6">
            GymHolic integrates with Google services to enable expert calendar
            connectivity and consultation scheduling. By using Google services
            through GymHolic, you agree to Google's applicable terms and
            privacy policies. GymHolic acts as an intermediary; Google's
            directly-applicable terms and policies govern the relationship between
            you and Google.
          </p>

          <h3 className="text-xl font-medium mb-3">
            Google Calendar Connection
          </h3>

          <p className="mb-6">
            Experts who connect their Google Calendar grant GymHolic permission
            to create and manage calendar events on their behalf for scheduled
            consultations. This access is limited to the minimum scope necessary
            for booking functionality and can be revoked at any time through the
            expert's GymHolic settings.
          </p>

          <h3 className="text-xl font-medium mb-3">
            Google Meet Integration
          </h3>

          <p className="mb-6">
            Consultations may include Google Meet conference links generated by
            GymHolic on behalf of the expert. Google Meet terms and privacy
            policies apply to the use of video conferencing features.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            Payments
          </h2>

          <p className="mb-6">
            GymHolic processes payments through Stripe. All payment card data is
            handled according to PCI DSS requirements. GymHolic does not store
            full credit card details; only Stripe payment tokens are retained.
          </p>

          <h3 className="text-xl font-medium mb-3">
            Consultation Fees
          </h3>

          <p className="mb-6">
            Consultation fees are set by the expert and processed through the
            GymHolic platform. All fees are in USD unless otherwise agreed.
            Refund policies are determined by the individual expert and should
            be agreed upon before booking.
          </p>
        </section>

        <section className="mb-8">
          <h2 className="text-2xl font-semibold mb-4">
            Liability
          </h2>

          <p className="mb-6">
            GymHolic provides platform facilitation only and does not guarantee
            specific outcomes from consultations. Experts are independent
            contractors responsible for their own services. GymHolic is not
            liable for any direct, indirect, incidental, special, consequential,
            or punitive damages, including without limitation loss of data,
            lost profits, incurred costs, or other damages, whether in an action
            in contract, tort, or otherwise.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Third-Party Services
          </h2>

          <p className="mb-6">
            GymHolic incorporates the following third-party services:
          </p>

          <ul className="list-disc list-inside mb-6 space-y-2">
            <li>
              <strong>Stripe:</strong> For payment processing. Stripe's
              Terms of Service apply: <a href="https://stripe.com/terms"
                target="_blank" rel="noopener noreferrer"
                >stripe.com/terms</a>
            </li>
            <li>
              <strong>Google Calendar/Meet:</strong> For calendar connectivity
              and video conferencing. Google's Terms of Service apply:
              <a href="https://policies.google.com/terms"
                target="_blank" rel="noopener noreferrer"
                >policies.google.com/terms</a>
            </li>
            <li>
              <strong>Upstash Redis:</strong> For shared data storage.
            </li>
            <li>
              <strong>Resend:</strong> For transactional email.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Modifications
          </h2>

          <p className="mb-6">
            GymHolic reserves the right to modify these Terms & Conditions at
            any time. We will attempt to provide notice of such modifications,
            but users are encouraged to review this page periodically. Your
            continued use of GymHolic after any such modifications constitutes
            your acceptance of the modified terms.
          </p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold mb-4">
            Governing Law
          </h2>

          <p className="mb-6">
            These Terms & Conditions shall be governed by and construed in
            accordance with the laws of the United Arab Emirates, without
            regard to its conflict of law principles.
          </p>
        </section>
      </main>
    </Layout>
  );
}