CREATE TABLE google_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    google_email VARCHAR(255) NOT NULL,
    encrypted_refresh_token VARCHAR(500) NOT NULL,
    calendar_id VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_google_connection_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);